from selenium.webdriver.chrome.service import Service
from selenium import webdriver
import time
from selenium.webdriver.common.by import By

service = Service(executable_path="/usr/local/bin/chromedriver")
#initialize web driver
with webdriver.Chrome(service=service) as driver:
    #navigate to the url
    # driver.get("https://adventofcode.com/2022/day/24")
    #find element by css selector
    # myDiv = driver.find_element(By.CSS_SELECTOR, 'div')
    # print(myDiv.get_attribute("innerHTML"))

  

    driver.get("https://github.com/login")
    # myDiv = driver.find_element(By.CSS_SELECTOR, 'input').send_keys("Test")
    # driver.find_element(By.CSS_SELECTOR, 'input')  #.send_keys("Test")
    # print(myDiv.get_attribute("innerHTML"))

    driver.find_element("xpath", "//input[@type='text']").send_keys("olof.sandell@protonmail.com")
    driver.find_element("xpath", "//input[@type='password']").send_keys("1iL%sR$4a*1J")
    driver.find_element("xpath", "//input[@type='submit']").click()
    driver.get("https://adventofcode.com/2022/auth/login")
    driver.find_element("xpath", '//a[contains(@href,"github")]').click()

   
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("261")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("260")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("259")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("258")
    driver.find_element("xpath", "//input[@type='submit']").click()
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("315")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("316")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("318")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("319")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("320")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("321")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("322")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("323")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("324")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("325")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("326")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("327")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("328")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("329")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("330")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("331")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("332")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("333")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("334")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("335")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("336")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("337")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("338")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("339")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("340")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("341")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("342")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    driver.get("https://adventofcode.com/2022/day/24")
    driver.find_element("xpath", "//input[@type='text']").send_keys("343")
    driver.find_element("xpath", "//input[@type='submit']").click()
    time.sleep(903)
    
    


